from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from math import inf
from random import Random
from typing import Dict, List, Optional, Sequence, Set, Tuple
from warnings import warn

from .instance import MESPPRCInstance, NodeType
from .label import Label, PERM_UNREACHABLE, REACHABLE, TEMP_UNREACHABLE


@dataclass(frozen=True)
class GeneratedRoute:
    """
    Single feasible route generated by Phase 1.

    `local_resources` are the per-route resources enforced during Phase 1 labeling.
    `global_resources` are accumulated in parallel but are not part of Phase 1
    feasibility. They are exported so Phase 2 can enforce route-combination limits.

    `first_customer_in_route` is the symmetry-breaking route-class identifier chosen
    when the first customer is visited.
    `customer_state_signature` preserves the final Phase 1 customer-state vector so
    Phase 2 can retain more structural information than a flat covered-customer set.
    """

    route_id: int
    cost: float
    local_resources: Sequence[float]
    global_resources: Sequence[float]
    covered_customers: Set[int]
    path: List[int]
    first_customer_in_route: int | None
    customer_state_signature: Sequence[int]


@dataclass
class Phase1Result:
    """
    Output of the Phase 1 route-generation step.

    `feasible_routes` contains every elementary source-to-sink route that satisfies the
    local Phase 1 constraints. The legacy `negative_cost_routes` field is kept for
    compatibility, but it is now just an alias for the exported feasible routes: route
    negativity is not a selection criterion anymore.
    """

    labels_at_sink: List[Label]
    feasible_routes: List[GeneratedRoute]
    negative_cost_routes: List[GeneratedRoute]
    all_label_buckets: Dict[int, List[Label]]

    @property
    def exported_routes(self) -> List[GeneratedRoute]:
        return self.feasible_routes


@dataclass
class _StateRecord:
    """
    Internal Phase 1 search state.

    The shared label only carries the Phase 1 local-resource state and customer
    reachability semantics. Route-level global resource contribution and the
    first-customer symmetry-breaking identifier are tracked next to the label so
    Phase 1 stays locally focused while exporting richer route metadata to Phase 2.
    """

    label: Label
    path: List[int]
    global_resources: List[float]
    first_customer_in_route: int | None


class Phase1Solver:
    """
    Phase 1 elementary single-trip route generation.

    This is a local-feasibility ESPPRC-style labeling routine:
    - labels enforce only local / per-route resource limits
    - labels use the richer unreachable-vector semantics
    - global / route-combination resources are accumulated separately and exported

    `label_limit` is a heuristic cap on kept labels per node. When it truncates a bucket
    the solver emits a warning because correctness is no longer guaranteed.
    """

    def __init__(
        self,
        instance: MESPPRCInstance,
        *,
        randomize_node_selection: bool = False,
        rng_seed: Optional[int] = None,
        label_limit: Optional[int] = None,
    ) -> None:
        self.instance = instance
        self.randomize_node_selection = randomize_node_selection
        self.label_limit = label_limit
        self.rng = Random(rng_seed)

        self.customer_ids: List[int] = []
        self.required_customer_ids: List[int] = []
        self.customer_index: Dict[int, int] = {}
        self.local_dim = 0
        self.global_dim = 0

        self._preprocessed = False
        self._label_limit_warned = False
        self._local_lower_bounds: Dict[int, Dict[int, List[float]]] = {}

    def solve(self) -> Phase1Result:
        self._ensure_preprocessed()

        source = self.instance.source
        sink = self.instance.sink
        if source is None:
            raise ValueError("Instance source is not defined.")
        if sink is None:
            raise ValueError("Instance sink is not defined.")

        buckets: Dict[int, List[_StateRecord]] = {
            node_id: [] for node_id in self.instance.nodes
        }
        initial = self._initial_state(source)
        buckets[source].append(initial)
        self._run_labeling_search(active_nodes=[source], buckets=buckets)

        sink_states = buckets[sink]
        sink_labels = [state.label for state in sink_states]
        feasible_routes = self._extract_routes_from_sink_states(sink_states)
        negative_cost_routes = list(feasible_routes)

        return Phase1Result(
            labels_at_sink=sink_labels,
            feasible_routes=feasible_routes,
            negative_cost_routes=negative_cost_routes,
            all_label_buckets={
                node_id: [state.label for state in states]
                for node_id, states in buckets.items()
            },
        )

    def _ensure_preprocessed(self) -> None:
        if self._preprocessed:
            return

        self.instance.validate()
        self.customer_ids = self.instance.customers()
        self.required_customer_ids = self.instance.required_customers()
        self.customer_index = {
            customer_id: idx for idx, customer_id in enumerate(self.customer_ids)
        }
        self.local_dim = len(self.instance.local_limits)
        self.global_dim = len(self.instance.global_limits)
        self._local_lower_bounds = self._compute_local_resource_lower_bounds()
        self._preprocessed = True

    def _initial_state(self, source: int) -> _StateRecord:
        self._ensure_preprocessed()

        initial_vector = self.refresh_customer_states(
            current_node=source,
            local_resources=[0.0] * self.local_dim,
            vector=[REACHABLE] * len(self.customer_ids),
        )
        label = Label(
            current_node=source,
            cost=0.0,
            resources=[0.0] * self.local_dim,
            unreachable_vector=initial_vector,
        )
        return _StateRecord(
            label=label,
            path=[source],
            global_resources=[0.0] * self.global_dim,
            first_customer_in_route=None,
        )

    def _select_next_active_node(self, active_nodes: List[int]) -> int:
        if self.randomize_node_selection and len(active_nodes) > 1:
            idx = self.rng.randrange(len(active_nodes))
            return active_nodes.pop(idx)
        return active_nodes.pop(0)

    def _run_labeling_search(
        self,
        *,
        active_nodes: List[int],
        buckets: Dict[int, List[object]],
    ) -> None:
        while active_nodes:
            node = self._select_next_active_node(active_nodes)
            changed_nodes = self._extend_from_node(node, buckets)
            for changed in changed_nodes:
                if changed not in active_nodes:
                    active_nodes.append(changed)

    def _extend_from_node(
        self,
        node: int,
        buckets: Dict[int, List[_StateRecord]],
    ) -> List[int]:
        changed_nodes: List[int] = []

        if node == self.instance.sink:
            return changed_nodes

        source_states = sorted(
            buckets[node],
            key=self._state_sort_key,
        )
        for state in source_states:
            for succ in self.instance.successors(node):
                new_state = self._try_extend(state, succ)
                if new_state is None:
                    continue

                changed = self._insert_with_dominance(new_state, buckets[succ])
                if changed and succ not in changed_nodes:
                    changed_nodes.append(succ)

        return changed_nodes

    def _try_extend(self, state: _StateRecord, succ: int) -> Optional[_StateRecord]:
        label = state.label
        current_node = label.current_node

        if succ in self.customer_index:
            idx = self.customer_index[succ]
            if not Label.is_reachable(label.unreachable_vector[idx]):
                return None

        if not self._arc_exists(current_node, succ):
            return None

        arc = self.instance.get_arc(current_node, succ)
        new_local = self._vec_add(list(label.resources), list(arc.local_res))
        if self.local_dim and not self._within_limits(new_local, self.instance.local_limits):
            return None

        new_global = self._vec_add(list(state.global_resources), list(arc.global_res))
        new_vector = list(label.unreachable_vector)

        new_first_customer = state.first_customer_in_route
        if succ in self.customer_index:
            idx = self.customer_index[succ]
            new_vector[idx] = self._next_visit_position(new_vector)
            if new_first_customer is None:
                new_first_customer = succ

        new_vector = self.refresh_customer_states(
            current_node=succ,
            local_resources=new_local,
            vector=new_vector,
        )
        new_label = Label(
            current_node=succ,
            cost=label.cost + arc.cost,
            resources=new_local,
            unreachable_vector=new_vector,
        )

        new_path = list(state.path)
        new_path.append(succ)
        return _StateRecord(
            label=new_label,
            path=new_path,
            global_resources=new_global,
            first_customer_in_route=new_first_customer,
        )

    def refresh_customer_states(
        self,
        *,
        current_node: int,
        local_resources: List[float],
        vector: List[int],
    ) -> List[int]:
        """
        Recompute customer reachability from the current partial state.

        Positive values (visited customers) and `-1` values (permanently unreachable
        customers) are absorbing. Among the remaining customers:
        - `0` means the customer is directly reachable now
        - `-2` means the customer is not directly reachable now but still cannot be
          safely ruled out from this label
        - `-1` is used only when a conservative label-relative impossibility proof is
          available
        """

        self._ensure_preprocessed()

        out = list(vector)
        changed = True
        while changed:
            changed = False
            for customer_id in self.customer_ids:
                idx = self.customer_index[customer_id]
                state = out[idx]
                if Label.is_visited(state) or Label.is_perm_unreachable(state):
                    continue

                if self.proves_permanent_unreachability(
                    customer_id=customer_id,
                    current_node=current_node,
                    local_resources=local_resources,
                    vector=out,
                ):
                    out[idx] = PERM_UNREACHABLE
                    changed = True

        for customer_id in self.customer_ids:
            idx = self.customer_index[customer_id]
            state = out[idx]
            if Label.is_visited(state) or Label.is_perm_unreachable(state):
                continue

            out[idx] = self.classify_customer_state(
                customer_id=customer_id,
                current_node=current_node,
                local_resources=local_resources,
                vector=out,
            )

        return out

    def classify_customer_state(
        self,
        *,
        customer_id: int,
        current_node: int,
        local_resources: List[float],
        vector: List[int],
    ) -> int:
        if self.can_currently_reach_customer(
            customer_id=customer_id,
            current_node=current_node,
            local_resources=local_resources,
            vector=vector,
        ):
            return REACHABLE

        if self.can_still_reach_customer(
            customer_id=customer_id,
            current_node=current_node,
            local_resources=local_resources,
            vector=vector,
        ):
            return TEMP_UNREACHABLE

        return TEMP_UNREACHABLE

    def can_currently_reach_customer(
        self,
        *,
        customer_id: int,
        current_node: int,
        local_resources: List[float],
        vector: List[int],
    ) -> bool:
        if not self._arc_exists(current_node, customer_id):
            return False

        arc = self.instance.get_arc(current_node, customer_id)
        candidate_local = self._vec_add(list(local_resources), list(arc.local_res))
        if self.local_dim and not self._within_limits(
            candidate_local,
            self.instance.local_limits,
        ):
            return False

        return self.can_reach_sink_after_customer(
            customer_id=customer_id,
            local_resources_after_customer=candidate_local,
            vector=vector,
        )

    def can_still_reach_customer(
        self,
        *,
        customer_id: int,
        current_node: int,
        local_resources: List[float],
        vector: List[int],
    ) -> bool:
        if not self._has_residual_path_to_customer(
            start=current_node,
            customer_id=customer_id,
            vector=vector,
        ):
            return False

        if not self._has_residual_path_after_visiting_customer(
            start=customer_id,
            target=self._sink_or_error(),
            customer_id=customer_id,
            vector=vector,
        ):
            return False

        return self._can_fit_customer_completion_lower_bound(
            current_node=current_node,
            customer_id=customer_id,
            local_resources=local_resources,
        )

    def lower_bound_to_customer(
        self,
        *,
        current_node: int,
        customer_id: int,
    ) -> List[float]:
        return self._lower_bound_between(current_node, customer_id)

    def lower_bound_customer_to_sink(
        self,
        *,
        customer_id: int,
    ) -> List[float]:
        return self._lower_bound_between(customer_id, self._sink_or_error())

    def can_reach_sink_after_customer(
        self,
        *,
        customer_id: int,
        local_resources_after_customer: List[float],
        vector: List[int],
    ) -> bool:
        if not self._has_residual_path_after_visiting_customer(
            start=customer_id,
            target=self._sink_or_error(),
            customer_id=customer_id,
            vector=vector,
        ):
            return False

        lower_bound = self.lower_bound_customer_to_sink(customer_id=customer_id)
        return self._can_fit_lower_bound(local_resources_after_customer, lower_bound)

    def proves_permanent_unreachability(
        self,
        *,
        customer_id: int,
        current_node: int,
        local_resources: List[float],
        vector: List[int],
    ) -> bool:
        """
        Return whether this label can safely declare the customer permanently lost.

        The proof is intentionally conservative and label-relative. A customer is marked
        permanently unreachable only when every completion of this partial route would
        fail to include it according to the residual-graph and lower-bound checks used
        here.
        """

        if not self._has_residual_path_to_customer(
            start=current_node,
            customer_id=customer_id,
            vector=vector,
        ):
            return True

        if not self._has_residual_path_after_visiting_customer(
            start=customer_id,
            target=self._sink_or_error(),
            customer_id=customer_id,
            vector=vector,
        ):
            return True

        if not self._can_fit_customer_completion_lower_bound(
            current_node=current_node,
            customer_id=customer_id,
            local_resources=local_resources,
        ):
            return True

        return False

    def _can_fit_customer_completion_lower_bound(
        self,
        *,
        current_node: int,
        customer_id: int,
        local_resources: List[float],
    ) -> bool:
        if self.local_dim == 0:
            return True

        to_customer = self.lower_bound_to_customer(
            current_node=current_node,
            customer_id=customer_id,
        )
        to_sink = self.lower_bound_customer_to_sink(customer_id=customer_id)
        if self._is_infinite_bound(to_customer) or self._is_infinite_bound(to_sink):
            return False

        return all(
            used + lb_customer + lb_sink <= limit
            for used, lb_customer, lb_sink, limit in zip(
                local_resources,
                to_customer,
                to_sink,
                self.instance.local_limits,
            )
        )

    def _has_residual_path_to_customer(
        self,
        *,
        start: int,
        customer_id: int,
        vector: List[int],
    ) -> bool:
        blocked = self._blocked_customers(vector, allowed_customers={customer_id, start})
        return self._has_path_in_residual_graph(start=start, target=customer_id, blocked=blocked)

    def _has_residual_path_after_visiting_customer(
        self,
        *,
        start: int,
        target: int,
        customer_id: int,
        vector: List[int],
    ) -> bool:
        blocked = self._blocked_customers(
            vector,
            allowed_customers={customer_id, start, target},
        )
        return self._has_path_in_residual_graph(start=start, target=target, blocked=blocked)

    def _blocked_customers(
        self,
        vector: List[int],
        allowed_customers: Set[int],
    ) -> Set[int]:
        blocked: Set[int] = set()
        for customer_id in self.customer_ids:
            if customer_id in allowed_customers:
                continue

            idx = self.customer_index[customer_id]
            if Label.is_permanently_lost(vector[idx]):
                blocked.add(customer_id)

        return blocked

    def _has_path_in_residual_graph(
        self,
        *,
        start: int,
        target: int,
        blocked: Set[int],
    ) -> bool:
        if start == target:
            return True

        blocked_nodes = set(blocked)
        blocked_nodes.discard(start)
        blocked_nodes.discard(target)

        queue: deque[int] = deque([start])
        seen = {start}
        while queue:
            node = queue.popleft()
            for succ in self.instance.successors(node):
                if succ in blocked_nodes or succ in seen:
                    continue
                if succ == target:
                    return True
                seen.add(succ)
                queue.append(succ)

        return False

    def _insert_with_dominance(
        self,
        new_state: object,
        bucket: List[object],
    ) -> bool:
        survivors: List[object] = []

        for old_state in bucket:
            if self._states_equivalent(old_state, new_state):
                return False
            if self._state_dominates(old_state, new_state):
                return False
            if not self._state_dominates(new_state, old_state):
                survivors.append(old_state)

        survivors.append(new_state)
        survivors.sort(key=self._state_sort_key)

        if self.label_limit is not None and len(survivors) > self.label_limit:
            if not self._label_limit_warned:
                warn(
                    "label_limit truncates non-dominated labels and is only a heuristic cap.",
                    RuntimeWarning,
                    stacklevel=2,
                )
                self._label_limit_warned = True
            survivors = survivors[: self.label_limit]

        bucket.clear()
        bucket.extend(survivors)
        return True

    def _states_equivalent(self, a: _StateRecord, b: _StateRecord) -> bool:
        return (
            a.label == b.label
            and a.global_resources == b.global_resources
            and a.path == b.path
            and a.first_customer_in_route == b.first_customer_in_route
        )

    def _state_sort_key(self, state: _StateRecord) -> tuple[object, ...]:
        return (
            state.label.cost,
            state.label.resources,
            state.global_resources,
            self._first_customer_sort_key(state.first_customer_in_route),
            state.path,
        )

    def _state_dominates(self, a: _StateRecord, b: _StateRecord) -> bool:
        if (
            a.first_customer_in_route is not None
            and b.first_customer_in_route is not None
            and a.first_customer_in_route != b.first_customer_in_route
        ):
            return self._is_better_canonical_phase1_representative(a, b)

        if not self._label_no_worse(a.label, b.label):
            return False

        if not self._vec_le(a.global_resources, b.global_resources):
            return False

        if self._label_strictly_better(a.label, b.label) or self._vec_lt(
            a.global_resources,
            b.global_resources,
        ):
            return True

        return self._is_better_canonical_phase1_representative(a, b)

    def _is_better_canonical_phase1_representative(
        self,
        a: _StateRecord,
        b: _StateRecord,
    ) -> bool:
        if a.label.current_node != b.label.current_node:
            return False
        if a.label.cost != b.label.cost:
            return False
        if a.label.resources != b.label.resources:
            return False
        if a.global_resources != b.global_resources:
            return False
        if self._collapsed_customer_states(a.label.unreachable_vector) != self._collapsed_customer_states(
            b.label.unreachable_vector
        ):
            return False

        return self._phase1_canonical_key(a) < self._phase1_canonical_key(b)

    def _phase1_canonical_key(self, state: _StateRecord) -> tuple[object, ...]:
        return (
            self._first_customer_sort_key(state.first_customer_in_route),
            tuple(self._visited_customer_set(state.label.unreachable_vector)),
            state.path,
        )

    def _dominates(self, a: Label, b: Label) -> bool:
        return self._label_no_worse(a, b) and self._label_strictly_better(a, b)

    def _label_no_worse(self, a: Label, b: Label) -> bool:
        if a.current_node != b.current_node:
            return False

        resources_le = self._vec_le(a.resources, b.resources)
        count_le = a.unreachable_count <= b.unreachable_count
        struct_le = self._customer_state_no_worse(
            a.unreachable_vector,
            b.unreachable_vector,
        )
        return a.cost <= b.cost and resources_le and count_le and struct_le

    def _label_strictly_better(self, a: Label, b: Label) -> bool:
        return (
            a.cost < b.cost
            or self._vec_lt(a.resources, b.resources)
            or a.unreachable_count < b.unreachable_count
            or self._customer_state_strictly_better(
                a.unreachable_vector,
                b.unreachable_vector,
            )
        )

    def _customer_state_no_worse(self, a: List[int], b: List[int]) -> bool:
        return all(
            self._customer_state_entry_no_worse(av, bv)
            for av, bv in zip(a, b)
        )

    def _customer_state_strictly_better(self, a: List[int], b: List[int]) -> bool:
        return any(
            self._customer_state_entry_strictly_better(av, bv)
            for av, bv in zip(a, b)
        )

    @staticmethod
    def _customer_state_entry_no_worse(a_value: int, b_value: int) -> bool:
        """
        Partial order used by Phase 1 dominance.

        Reachable is strongest, temporary loss is weaker, and permanent loss is weakest.
        Visited and permanently unreachable customers are both permanent losses for
        future route extension, but they are kept distinct so Phase 1 can still export
        structurally different complete routes to Phase 2.
        """

        if Label.is_reachable(a_value):
            return True
        if Label.is_temp_unreachable(a_value):
            return not Label.is_reachable(b_value)
        if Label.is_perm_unreachable(a_value):
            return Label.is_perm_unreachable(b_value)
        if Label.is_visited(a_value):
            return Label.is_visited(b_value)
        raise ValueError("Invalid Phase 1 customer state.")

    @staticmethod
    def _customer_state_entry_strictly_better(a_value: int, b_value: int) -> bool:
        if not Phase1Solver._customer_state_entry_no_worse(a_value, b_value):
            return False
        if Label.is_reachable(a_value):
            return not Label.is_reachable(b_value)
        if Label.is_temp_unreachable(a_value):
            return Label.is_perm_unreachable(b_value) or Label.is_visited(b_value)
        return False

    def _collapsed_customer_states(self, vector: Sequence[int]) -> Tuple[int, ...]:
        collapsed: List[int] = []
        for value in vector:
            if Label.is_visited(value):
                collapsed.append(1)
            else:
                collapsed.append(int(value))
        return tuple(collapsed)

    def _visited_customer_set(self, vector: Sequence[int]) -> Tuple[int, ...]:
        return tuple(
            customer_id
            for customer_id in self.customer_ids
            if Label.is_visited(vector[self.customer_index[customer_id]])
        )

    def _extract_routes_from_sink_states(
        self,
        sink_states: List[_StateRecord],
    ) -> List[GeneratedRoute]:
        routes: List[GeneratedRoute] = []

        ordered_states = sorted(
            sink_states,
            key=lambda state: (
                self._first_customer_sort_key(state.first_customer_in_route),
                state.label.cost,
                state.global_resources,
                state.path,
            ),
        )

        for route_id, state in enumerate(ordered_states, start=1):
            path = list(state.path)
            covered_customers = {
                node_id
                for node_id in path
                if self.instance.nodes[node_id].node_type == NodeType.CUSTOMER
            }
            routes.append(
                GeneratedRoute(
                    route_id=route_id,
                    cost=state.label.cost,
                    local_resources=list(state.label.resources),
                    global_resources=list(state.global_resources),
                    covered_customers=covered_customers,
                    path=path,
                    first_customer_in_route=state.first_customer_in_route,
                    customer_state_signature=list(state.label.unreachable_vector),
                )
            )

        return routes

    def _compute_local_resource_lower_bounds(self) -> Dict[int, Dict[int, List[float]]]:
        if self.local_dim == 0:
            return {}

        sink = self._sink_or_error()
        targets = list(self.customer_ids)
        if sink not in targets:
            targets.append(sink)

        lower_bounds: Dict[int, Dict[int, List[float]]] = {}
        for target in targets:
            per_dimension = [
                self._single_dimension_reverse_shortest_paths(target=target, dimension=dim)
                for dim in range(self.local_dim)
            ]
            lower_bounds[target] = {
                node_id: [per_dimension[dim][node_id] for dim in range(self.local_dim)]
                for node_id in self.instance.nodes
            }

        return lower_bounds

    def _single_dimension_reverse_shortest_paths(
        self,
        *,
        target: int,
        dimension: int,
    ) -> Dict[int, float]:
        distance = {node_id: inf for node_id in self.instance.nodes}
        distance[target] = 0.0

        node_count = len(self.instance.nodes)
        for _ in range(max(node_count - 1, 0)):
            updated = False
            for arc in self.instance.arcs.values():
                head_distance = distance[arc.head]
                if head_distance == inf:
                    continue

                candidate = float(arc.local_res[dimension]) + head_distance
                if candidate < distance[arc.tail]:
                    distance[arc.tail] = candidate
                    updated = True

            if not updated:
                break

        return distance

    def _lower_bound_between(self, start: int, target: int) -> List[float]:
        if self.local_dim == 0:
            return []

        target_bounds = self._local_lower_bounds.get(target)
        if target_bounds is None:
            return [inf] * self.local_dim
        return list(target_bounds.get(start, [inf] * self.local_dim))

    def _can_fit_lower_bound(
        self,
        used_resources: List[float],
        lower_bound: List[float],
    ) -> bool:
        if self.local_dim == 0:
            return True
        if self._is_infinite_bound(lower_bound):
            return False
        return all(
            used + lb <= limit
            for used, lb, limit in zip(
                used_resources,
                lower_bound,
                self.instance.local_limits,
            )
        )

    @staticmethod
    def _is_infinite_bound(lower_bound: List[float]) -> bool:
        return any(value == inf for value in lower_bound)

    def _first_customer_sort_key(self, customer_id: int | None) -> tuple[int, int]:
        if customer_id is None:
            return (1, inf)
        return (0, customer_id)

    def _sink_or_error(self) -> int:
        sink = self.instance.sink
        if sink is None:
            raise ValueError("Instance sink is not defined.")
        return sink

    def _arc_exists(self, i: int, j: int) -> bool:
        return (i, j) in self.instance.arcs

    @staticmethod
    def _next_visit_position(vector: List[int]) -> int:
        best = 0
        for value in vector:
            if value > best:
                best = value
        return best + 1

    @staticmethod
    def _vec_add(a: List[float], b: List[float]) -> List[float]:
        if not a and not b:
            return []
        if len(a) != len(b):
            raise ValueError("Resource vectors have incompatible dimensions.")
        return [x + y for x, y in zip(a, b)]

    @staticmethod
    def _within_limits(vec: List[float], limits: List[float]) -> bool:
        if len(vec) != len(limits):
            return False
        return all(v <= lim for v, lim in zip(vec, limits))

    @staticmethod
    def _vec_le(a: List[float], b: List[float]) -> bool:
        return len(a) == len(b) and all(x <= y for x, y in zip(a, b))

    @staticmethod
    def _vec_lt(a: List[float], b: List[float]) -> bool:
        return len(a) == len(b) and any(x < y for x, y in zip(a, b)) and all(
            x <= y for x, y in zip(a, b)
        )
