"""
Build / refresh the bundled LRSP instance library.

Sweeps a (size × regime × seed) grid through `instance_generator.generate_instance`
and writes one `.lrsp.json` per instance plus a parallel `.txt` (Akca format,
for direct C-runner consumption) under `lrsp_solver/instance_db/`.

Run as a module:

    python -m lrsp_solver.instance_database_builder
    python -m lrsp_solver.instance_database_builder --clean
    python -m lrsp_solver.instance_database_builder --sizes 5,10,15,20 --regimes moderate,tight

The manifest at `lrsp_solver/instance_db/manifest.json` is rewritten from
scratch every run, so any `.json`/`.txt` left behind in the folder that the
manifest doesn't mention will be invisible to readers (and removed by
`--clean`).
"""

from __future__ import annotations

import argparse
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List

from .instance_database import (
    InstanceRecord,
    database_directory,
    instances_directory,
    write_manifest,
)
from .instance_generator import (
    GeneratorConfig,
    LRSPGeneratorError,
    REGIMES,
    generate_instance,
    regime_config,
)
from .instance_io import write_akca_txt, write_lrsp_json


# ---------------------------------------------------------------------------
# Default sweep — the bundled corpus this builder produces by default.
# ---------------------------------------------------------------------------

DEFAULT_SIZES: List[tuple[int, int]] = [
    # (num_customers, num_facilities)
    (5,  2),
    (8,  2),
    (10, 3),
    (15, 3),
    (20, 4),
    (25, 5),
    (30, 5),
    (40, 6),
    (50, 8),
]

DEFAULT_REGIMES: List[str] = ["easy", "moderate", "tight"]
DEFAULT_SEEDS: List[int] = [1, 2, 3]


@dataclass(slots=True)
class BuildResult:
    written: List[InstanceRecord]
    skipped: List[tuple[GeneratorConfig, str]]


def build_database(
    *,
    sizes: List[tuple[int, int]] = DEFAULT_SIZES,
    regimes: List[str] = DEFAULT_REGIMES,
    seeds: List[int] = DEFAULT_SEEDS,
    clean: bool = False,
    write_txt: bool = True,
    db_dir: Path | None = None,
) -> BuildResult:
    """
    Generate the corpus and write JSON + .txt companions + manifest.

    `clean=True` empties the instances folder before writing.
    """

    db_dir = db_dir or database_directory()
    inst_dir = instances_directory() if db_dir == database_directory() else db_dir / "instances"
    if clean and inst_dir.exists():
        shutil.rmtree(inst_dir)
    inst_dir.mkdir(parents=True, exist_ok=True)

    written: List[InstanceRecord] = []
    skipped: List[tuple[GeneratorConfig, str]] = []

    for n, F in sizes:
        for regime in regimes:
            for seed in seeds:
                cfg = regime_config(
                    regime,
                    num_customers=n,
                    num_facilities=F,
                    seed=seed,
                )
                try:
                    instance = generate_instance(cfg)
                except LRSPGeneratorError as exc:
                    skipped.append((cfg, str(exc)))
                    print(f"  skip {cfg.name or '<auto>'}: {exc}",
                          file=sys.stderr)
                    continue

                instance_id = (
                    f"lrsp_n{n:03d}_f{F:02d}_{regime}_s{seed}"
                )
                json_path = inst_dir / f"{instance_id}.lrsp.json"
                txt_path = inst_dir / f"{instance_id}.txt" if write_txt else None

                # Override the auto-generated name with the canonical id so
                # the JSON's `name` field matches the file stem.
                instance = type(instance)(
                    name=instance_id,
                    customers=instance.customers,
                    facilities=instance.facilities,
                    vehicle_capacity=instance.vehicle_capacity,
                    vehicle_fixed_cost=instance.vehicle_fixed_cost,
                    vehicle_operating_cost=instance.vehicle_operating_cost,
                    vehicle_time_limit=instance.vehicle_time_limit,
                    notes=[
                        f"Generated by lrsp_solver.instance_generator",
                        f"regime={regime} seed={seed}",
                        f"num_customers={n} num_facilities={F}",
                    ],
                )

                write_lrsp_json(instance, json_path)
                if txt_path is not None:
                    write_akca_txt(instance, txt_path)

                written.append(InstanceRecord(
                    instance_id=instance_id,
                    json_path=json_path,
                    txt_path=txt_path,
                    num_customers=n,
                    num_facilities=F,
                    regime=regime,
                    seed=seed,
                    extras={
                        "vehicle_capacity": instance.vehicle_capacity,
                        "vehicle_time_limit": instance.vehicle_time_limit,
                        "total_demand": sum(c.demand for c in instance.customers),
                    },
                ))

    write_manifest(written)
    return BuildResult(written=written, skipped=skipped)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_sizes(arg: str) -> List[tuple[int, int]]:
    """Parse `5x2,10x3,...`. Pure 'n' means F = max(2, ceil(n/5))."""
    out: List[tuple[int, int]] = []
    for token in arg.split(","):
        token = token.strip()
        if "x" in token:
            n_s, f_s = token.split("x", 1)
            out.append((int(n_s), int(f_s)))
        else:
            n = int(token)
            f = max(2, (n + 4) // 5)
            out.append((n, f))
    return out


def main(argv: List[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="(Re)build the bundled LRSP instance library.",
    )
    ap.add_argument("--sizes",
                    type=_parse_sizes,
                    default=DEFAULT_SIZES,
                    help="Comma-separated list of `<n>x<F>` pairs (e.g. "
                         "`5x2,10x3,20x4`). Bare `<n>` picks F by rule of "
                         "thumb. Default: built-in sweep covering n=5..50.")
    ap.add_argument("--regimes",
                    type=lambda s: [t.strip() for t in s.split(",")],
                    default=DEFAULT_REGIMES,
                    help=f"Comma-separated regimes from {sorted(REGIMES)}. "
                         f"Default: {DEFAULT_REGIMES}.")
    ap.add_argument("--seeds",
                    type=lambda s: [int(t) for t in s.split(",")],
                    default=DEFAULT_SEEDS,
                    help="Comma-separated integer seeds. Default: 1,2,3.")
    ap.add_argument("--clean", action="store_true",
                    help="Empty the instances folder before writing.")
    ap.add_argument("--no-txt", action="store_true",
                    help="Skip writing Akca .txt companions (JSON only).")
    args = ap.parse_args(argv)

    result = build_database(
        sizes=args.sizes,
        regimes=args.regimes,
        seeds=args.seeds,
        clean=args.clean,
        write_txt=not args.no_txt,
    )

    print(f"\nWrote {len(result.written)} instance(s) to "
          f"{database_directory().relative_to(Path.cwd()) if database_directory().is_relative_to(Path.cwd()) else database_directory()}")
    if result.skipped:
        print(f"Skipped {len(result.skipped)} infeasible "
              f"configuration(s); see stderr for details.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
